### ISSUE TITLE
Version specified in multi-tenancy-gitops-infra/storage/Chart.yaml isn't 0.1.2

### ISSUE THREAD

**Issue by David-M-IBM** [cloud-native-toolkit/multi-tenancy-gitops-infra#28]
In [the ocs-operator Chart
](https://github.com/cloud-native-toolkit/multi-tenancy-gitops-infra/blob/master/storage/Chart.yaml) It looks like an older version of the [storage-operatorgroup template
](https://github.com/cloud-native-toolkit/toolkit-charts/blob/main/stable/odf-operator/templates/storage-operatorgroup.yaml) is specified. I get an error in argocd after running the infra-mod.sh script saying "error validating data: ValidationError(OperatorGroup.status): missing required field “lastUpdated” in com.coreos.operators.v1.OperatorGroup.status" 
<img width="1405" alt="image (6)" src="https://user-images.githubusercontent.com/83517881/160972001-de87f212-a0a8-4786-adb2-80bb114f8d93.png">
and I think it is due to the multi-tenancy-gitops-infra storage chart not specifying the newer version (0.1.2) of the helm chart that added 
```
status:
  lastUpdated: nill
```
  
```
apiVersion: v2
name: ocs-operator
description: Deployment of OpenShift Data Foudnation
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: odf-operator
    version: 0.1.0
    repository: https://cloud-native-toolkit.github.io/toolkit-charts/
```
*also foundation is misspelled in the description
